'use strict';

module.exports =  {
	get: 'GET',
	post: 'POST',
	put: 'PUT',
	remove: 'DELETE',
	finalCatch:'finally',
	currentlyEffective: "Currently Effective",
	effectiveOn: "Effective on ",
	effectiveSince: "Effective since ",
	effective: "Effective ",
	country: "US",
	endDate: "2099-12-31",
	yearStart: 1900,
	statusCode: "200",
	success: "success",
	danger: "danger",
	warning: "warning",
	on: "on",
	since: "since",
	dateFormat: "yyyy-MM-dd",
	fullDateFormat: "MMMM dd,yyyy",
	dateFormatUS: "MM/dd/yyyy",
	dateTimeFormatUS: "MM/dd/yyyy HH:mm:ss",
	sectionName: 'name',
	sectionAddress: 'address',
	sectionInfo: 'info',
	genderMale: "Male",
	genderFemale: "Female",
	genderMaleKey: "M",
	primaryNameType: 'PRI',
	preferredNameType: 'PRF',
	emitName: 'name',
	emitAddress: 'address',
	emitEmail: 'email',
	emitPhoneNumber: 'phone',
	emitAlert: 'alert',
	emitDDAlert: 'ddAlert',
	emitNoData: 'ddNoDataAlert',
	emitLogoName: 'logoName',
	mediaTypeEmail: 'Email',
	mediaTypePhone: 'Phone',
	broadcastContact: 'toggleContact',
	zeroDoublePrecision: "0.00",
	retirementPlanGoalAmountColorCode: '#084B8A',
	retirementPlanFederalColorCode: 'gray',
	retirementPlanFederalAmountLabel: 'Federal Amount',
	retirementPlanGoalAmountLabel: "Goal Amount",
	retirementPlanYTDColorCode: "#084B8A",
	retirementPlanYTDLabel: "Ytd Contribution",
	retirementPlanGoalAmount: 1000,
	section: "retirementPlan",
	goalAmountText: "setGoalAmt",
	exemptValue: "checked",
	check_index: "curEffDate",
	modules: "global,home,profile,money,benefits,company,manageEmp",
	defaultLanguage: "en-US",
	i18nPath: "assets/i18n/",
	docLocContext: "/api-content",
	directDeposit: {
		accountType: {
			checkKey: "check",
			checkValue: "check",
			newKey: "new",
			newValue: "New Account"
		},
		remainingAmount: "Remaining Amount",
		fullAmount:"Full Amount",
		accountName: "Account Name",
		opNew: "new",
		opAdd: "add"
	},
	taxWithHoldings: {
		statesToUpdateLocalTax : ['IN','OH','MD'],
		statesToDisableStateSection : ['AK','FL','NV','NH','SD','TN','TX','WA','WY'],
		statesToDisableAllowances : ['NE']
	},
	timezone :"EDT",
	EST: -5.00,
	EDT: -4.00,
	PDT: -7.00,
	PST: -8.00
};
